---
- name: Install httpd pkg
  hosts: all
  become: true
  tasks:
  - name: my httpd pkg
    yum:
      name: httpd
      state: installed
  - name: start httpd servicee
    service:
      name: httpd
      state: started  
